ALTER TABLE articles ADD COLUMN image_url text;
ALTER TABLE articles ADD COLUMN image_credit text;
CREATE TABLE contributors (
 id text PRIMARY KEY, name text NOT NULL,
 kind text NOT NULL CHECK (kind IN ('journalist','expert')),
 field text CHECK (field IN ('Political Science','Public Administration/Governance','Economics','Law','Environment/Climate Policy','Public Health')),
 credentials text NOT NULL, affiliation text,
 conflicts jsonb NOT NULL DEFAULT '[]' CHECK (jsonb_typeof(conflicts) = 'array'),
 bio text NOT NULL, portfolio_url text, is_sample boolean NOT NULL DEFAULT false,
 created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE commentary (
 id text PRIMARY KEY, story_id text NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
 contributor_id text NOT NULL REFERENCES contributors(id) ON DELETE CASCADE,
 title text NOT NULL, body text NOT NULL CHECK (char_length(body) <= 1200),
 published_at timestamptz NOT NULL DEFAULT now(), is_sample boolean NOT NULL DEFAULT false
);
CREATE INDEX commentary_story ON commentary(story_id,published_at DESC);
CREATE INDEX commentary_contributor ON commentary(contributor_id);
CREATE TABLE story_links (
 story_id text NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
 related_story_id text NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
 relation text NOT NULL CHECK (relation IN ('earlier','later','developing')),
 confidence real NOT NULL CHECK (confidence BETWEEN 0 AND 1), created_at timestamptz NOT NULL DEFAULT now(),
 PRIMARY KEY(story_id,related_story_id), CHECK (story_id <> related_story_id)
);
CREATE INDEX story_links_related ON story_links(related_story_id);
CREATE TABLE flags (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 kind text NOT NULL CHECK (kind IN ('coverage_mismatch','related_mismatch','source_miscategorized')),
 story_id text REFERENCES stories(id) ON DELETE SET NULL, target_id text NOT NULL,
 note text NOT NULL CHECK (char_length(note) <= 500),
 created_at timestamptz NOT NULL DEFAULT now(), status text NOT NULL DEFAULT 'open'
);
CREATE INDEX flags_status ON flags(status,created_at DESC);
CREATE TABLE newsletter_signups (email text PRIMARY KEY,created_at timestamptz NOT NULL DEFAULT now(),confirmed boolean NOT NULL DEFAULT false);
