-- Story IDs are historical references: retain audit rows when 14-day story pruning runs.
CREATE TABLE editions (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 edition_at timestamptz NOT NULL UNIQUE, window_label text NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE edition_placements (
 edition_id bigint NOT NULL REFERENCES editions(id) ON DELETE CASCADE,
 story_id text NOT NULL,
 slot text NOT NULL CHECK (slot IN ('lead','briefing','featured','top')),
 rank int NOT NULL CHECK (rank > 0), score real NOT NULL,
 subscores jsonb NOT NULL,
 PRIMARY KEY (edition_id,slot,rank), UNIQUE (edition_id,slot,story_id)
);
CREATE TABLE story_scores (
 story_id text NOT NULL,
 scored_at timestamptz NOT NULL, score real NOT NULL, subscores jsonb NOT NULL,
 PRIMARY KEY (story_id,scored_at)
);
CREATE INDEX story_scores_time ON story_scores(scored_at DESC);
DO $$ DECLARE t text; r text; BEGIN
 FOREACH t IN ARRAY ARRAY['editions','edition_placements','story_scores'] LOOP
  EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t);
  FOREACH r IN ARRAY ARRAY['anon','authenticated'] LOOP
   IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname=r) THEN EXECUTE format('REVOKE ALL ON public.%I FROM %I',t,r); END IF;
  END LOOP;
 END LOOP;
END $$;
