// Source registry. One entry per publisher/agency. Ingestion reads this and
// upserts into `sources`. Feed URLs MUST be verified live before `verified: true`
// (see scripts/check-feeds.ts). Ownership is factual only (§22, §26) — no
// editorializing — and every ownership statement cites where it came from.
import type { DataStatusId, LanguageId, RegionId, SourceTypeId } from "@/lib/taxonomy";

export interface FeedSource {
  id: string;
  name: string;
  type: SourceTypeId;
  homepage: string;
  feeds: string[]; // one or more RSS/Atom URLs; empty = headline + link only
  ownership: string;
  ownershipSource: string;
  dataStatus: DataStatusId;
  paywalled?: boolean;
  regions: RegionId[]; // primary regions covered
  languages: LanguageId[];
  topics?: string[];
  /** Fact-check publisher: items become `fact_checks` rows, not articles. */
  factCheck?: boolean;
  verified: boolean; // set by scripts/check-feeds.ts output review
  /** Why a source has no working feed (shown nowhere in UI; for ops). */
  feedNote?: string;
}

export const FEEDS: FeedSource[] = [
  // ---- National Media ----
  {
    id: "inquirer",
    name: "Inquirer.net",
    type: "national",
    homepage: "https://www.inquirer.net",
    feeds: ["https://newsinfo.inquirer.net/feed"],
    ownership: "Philippine Daily Inquirer, Inc. (Inquirer Group)",
    ownershipSource: "Publisher's corporate information page",
    dataStatus: "feed",
    paywalled: false,
    regions: ["ncr"],
    languages: ["en"],
    verified: true,
  },
  {
    id: "gma-news",
    name: "GMA News Online",
    type: "national",
    homepage: "https://www.gmanetwork.com/news/",
    feeds: ["https://data.gmanetwork.com/gno/rss/news/feed.xml"],
    ownership: "GMA Network, Inc.",
    ownershipSource: "GMA Network corporate filings (PSE)",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en", "fil"],
    verified: true,
  },
  {
    id: "philstar",
    name: "The Philippine Star",
    type: "national",
    homepage: "https://www.philstar.com",
    feeds: ["https://www.philstar.com/rss/headlines", "https://www.philstar.com/rss/nation"],
    ownership: "Philstar Global Corp. (MediaQuest Holdings group)",
    ownershipSource: "Publisher's About page",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en"],
    verified: true,
  },
  {
    id: "abs-cbn",
    name: "ABS-CBN News",
    type: "national",
    homepage: "https://www.abs-cbn.com/news",
    feeds: ["https://www.abs-cbn.com/feed/"],
    ownership: "ABS-CBN Corporation (Lopez Group)",
    ownershipSource: "ABS-CBN corporate filings (PSE)",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en", "fil"],
    verified: true,
  },
  {
    id: "manila-bulletin",
    name: "Manila Bulletin",
    type: "national",
    homepage: "https://mb.com.ph",
    feeds: [],
    ownership: "Manila Bulletin Publishing Corporation",
    ownershipSource: "Publisher's About page",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en"],
    verified: false,
    feedNote: "HTTP 403 (bot-blocked) as of 2026-09-27; candidate for a data partnership",
  },
  {
    id: "manila-times",
    name: "The Manila Times",
    type: "national",
    homepage: "https://www.manilatimes.net",
    feeds: ["https://www.manilatimes.net/news/feed/"],
    ownership: "The Manila Times Publishing Corporation",
    ownershipSource: "Publisher's About page",
    dataStatus: "feed",
    paywalled: true,
    regions: ["ncr"],
    languages: ["en"],
    verified: true,
  },
  {
    id: "manila-standard",
    name: "Manila Standard",
    type: "national",
    homepage: "https://manilastandard.net",
    feeds: ["https://manilastandard.net/feed"],
    ownership: "Philippine Manila Standard Publishing, Inc.",
    ownershipSource: "Publisher's About page",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en"],
    verified: true,
  },
  {
    id: "businessworld",
    name: "BusinessWorld",
    type: "national",
    homepage: "https://www.bworldonline.com",
    feeds: ["https://www.bworldonline.com/feed/"],
    ownership: "BusinessWorld Publishing Corporation",
    ownershipSource: "Publisher's About page",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en"],
    topics: ["Economy", "Business"],
    verified: true,
  },
  {
    id: "businessmirror",
    name: "BusinessMirror",
    type: "national",
    homepage: "https://businessmirror.com.ph",
    feeds: [],
    ownership: "Philippine Business Daily Mirror Publishing, Inc.",
    ownershipSource: "Publisher's About page",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en"],
    topics: ["Economy", "Business"],
    verified: false,
    feedNote: "HTTP 403 (bot-blocked) as of 2026-09-27; candidate for a data partnership",
  },
  {
    id: "abante",
    name: "Abante",
    type: "national",
    homepage: "https://www.abante.com.ph",
    feeds: ["https://www.abante.com.ph/rss.xml"],
    ownership: "Monica Publishing Corporation",
    ownershipSource: "Publisher's About page",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["fil"],
    verified: true,
  },

  // ---- Independent ----
  {
    id: "rappler",
    name: "Rappler",
    type: "independent",
    homepage: "https://www.rappler.com",
    feeds: ["https://www.rappler.com/feed/"],
    ownership: "Rappler, Inc. (majority Filipino journalist-owned)",
    ownershipSource: "Rappler About page",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en", "fil"],
    verified: true,
  },
  {
    id: "pcij",
    name: "Philippine Center for Investigative Journalism",
    type: "independent",
    homepage: "https://pcij.org",
    feeds: ["https://pcij.org/feed/"],
    ownership: "Nonprofit, non-stock media foundation",
    ownershipSource: "PCIJ About page",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en"],
    verified: true,
  },
  {
    id: "bulatlat",
    name: "Bulatlat",
    type: "independent",
    homepage: "https://www.bulatlat.com",
    feeds: ["https://www.bulatlat.com/feed/"],
    ownership: "Independently owned (alternative media)",
    ownershipSource: "Bulatlat About page",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en", "fil"],
    verified: true,
  },
  {
    id: "mindanews",
    name: "MindaNews",
    type: "independent",
    homepage: "https://www.mindanews.com",
    feeds: [],
    ownership: "Mindanao News and Information Cooperative Center",
    ownershipSource: "MindaNews About page",
    dataStatus: "feed",
    regions: ["r11", "r10", "r12", "barmm", "r9", "r13"],
    languages: ["en"],
    verified: false,
    feedNote: "HTTP 403 (bot-blocked) as of 2026-09-27; candidate for a data partnership",
  },

  // ---- Fact-checkers (feed items become fact_checks, used to suppress Social blindspots) ----
  {
    id: "vera-files",
    name: "VERA Files",
    type: "independent",
    homepage: "https://verafiles.org",
    feeds: [],
    ownership: "Nonprofit media organization",
    ownershipSource: "VERA Files About page",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en", "fil"],
    factCheck: true,
    verified: false,
    feedNote: "no RSS document found as of 2026-09-27; candidate for a data partnership",
  },
  {
    id: "rappler-factcheck",
    name: "Rappler Fact Check",
    type: "independent",
    homepage: "https://www.rappler.com/newsbreak/fact-check/",
    feeds: ["https://www.rappler.com/newsbreak/fact-check/feed/"],
    ownership: "Rappler, Inc.",
    ownershipSource: "Rappler About page",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en", "fil"],
    factCheck: true,
    verified: true,
  },

  // ---- State-Run Media ----
  {
    id: "pna",
    name: "Philippine News Agency",
    type: "state",
    homepage: "https://www.pna.gov.ph",
    feeds: [],
    ownership: "Government of the Philippines (Presidential Communications Office)",
    ownershipSource: "PNA About page",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en"],
    verified: false,
    feedNote: "HTTP 404, no feed discovered as of 2026-09-27; candidate for a data partnership",
  },
  {
    id: "ptv",
    name: "PTV News",
    type: "state",
    homepage: "https://ptvnews.ph",
    feeds: ["https://ptvnews.ph/feed/"],
    ownership: "People's Television Network, Inc. (government-owned)",
    ownershipSource: "PTV About page",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en", "fil"],
    verified: true,
  },

  // ---- Government Statement ----
  {
    id: "pia",
    name: "Philippine Information Agency",
    type: "government",
    homepage: "https://pia.gov.ph",
    feeds: [],
    ownership: "Government of the Philippines (attached agency, PCO)",
    ownershipSource: "PIA About page",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en", "fil"],
    verified: false,
    feedNote: "HTTP 403 (bot-blocked) as of 2026-09-27; candidate for a data partnership",
  },
  {
    id: "senate",
    name: "Senate of the Philippines (Press Releases)",
    type: "government",
    homepage: "https://legacy.senate.gov.ph/press_release/",
    feeds: [],
    ownership: "Senate of the Philippines",
    ownershipSource: "Official website",
    dataStatus: "link",
    regions: ["ncr"],
    languages: ["en"],
    verified: false,
    feedNote: "no public feed as of 2026-09-27; candidate for a data partnership",
  },

  // ---- Primary Document ----
  {
    id: "official-gazette",
    name: "Official Gazette",
    type: "primary",
    homepage: "https://www.officialgazette.gov.ph",
    feeds: ["https://www.officialgazette.gov.ph/feed/"],
    ownership: "Government of the Philippines (Presidential Communications Office)",
    ownershipSource: "Official website",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en"],
    verified: true,
  },

  // ---- Regional Media ----
  {
    id: "sunstar",
    name: "SunStar",
    type: "regional",
    homepage: "https://www.sunstar.com.ph",
    feeds: ["https://www.sunstar.com.ph/feed/"],
    ownership: "SunStar Publishing, Inc.",
    ownershipSource: "SunStar About page",
    dataStatus: "feed",
    regions: ["r7", "r11", "r10", "r3", "car", "nir"],
    languages: ["en", "ceb"],
    verified: true,
  },
  {
    id: "panay-news",
    name: "Panay News",
    type: "regional",
    homepage: "https://www.panaynews.net",
    feeds: ["https://www.panaynews.net/feed/"],
    ownership: "Independently owned",
    ownershipSource: "Publisher's About page",
    dataStatus: "feed",
    regions: ["r6"],
    languages: ["en", "hil"],
    verified: true,
  },
  {
    id: "daily-guardian",
    name: "Daily Guardian",
    type: "regional",
    homepage: "https://dailyguardian.com.ph",
    feeds: [],
    ownership: "Independently owned",
    ownershipSource: "Publisher's About page",
    dataStatus: "feed",
    regions: ["r6"],
    languages: ["en"],
    verified: false,
    feedNote: "HTTP 403 (bot-blocked) as of 2026-09-27; candidate for a data partnership",
  },
  {
    id: "mindanao-times",
    name: "Mindanao Times",
    type: "regional",
    homepage: "https://mindanaotimes.com.ph",
    feeds: ["https://mindanaotimes.com.ph/feed/"],
    ownership: "Independently owned",
    ownershipSource: "Publisher's About page",
    dataStatus: "feed",
    regions: ["r11"],
    languages: ["en"],
    verified: true,
  },
  {
    id: "edge-davao",
    name: "Edge Davao",
    type: "regional",
    homepage: "https://edgedavao.net",
    feeds: ["https://edgedavao.net/feed/"],
    ownership: "Independently owned",
    ownershipSource: "Publisher's About page",
    dataStatus: "feed",
    regions: ["r11"],
    languages: ["en"],
    verified: true,
  },
  {
    id: "punto",
    name: "Punto! Central Luzon",
    type: "regional",
    homepage: "https://punto.com.ph",
    feeds: ["https://punto.com.ph/feed/"],
    ownership: "Independently owned",
    ownershipSource: "Publisher's About page",
    dataStatus: "feed",
    regions: ["r3"],
    languages: ["en", "fil"],
    verified: true,
  },
  {
    id: "baguio-midland",
    name: "Baguio Midland Courier",
    type: "regional",
    homepage: "https://www.baguiomidlandcourier.com.ph",
    feeds: [],
    ownership: "Independently owned",
    ownershipSource: "Publisher's About page",
    dataStatus: "feed",
    regions: ["car"],
    languages: ["en"],
    verified: false,
    feedNote: "connection failed as of 2026-09-27; candidate for a data partnership",
  },

  // ---- Community ----
  {
    id: "nordis",
    name: "Northern Dispatch",
    type: "community",
    homepage: "https://nordis.net",
    feeds: [],
    ownership: "Community-based media organization",
    ownershipSource: "Nordis About page",
    dataStatus: "feed",
    regions: ["car", "r1", "r2"],
    languages: ["en", "ilo"],
    verified: false,
    feedNote: "HTTP 429 (rate-limited) as of 2026-09-27; candidate for a data partnership",
  },
];
