// Source registry. One entry per publisher/agency. Ingestion reads this and
// upserts into `sources`. Feed URLs MUST be verified live before `verified: true`
// (see scripts/check-feeds.ts). Ownership is factual only (§22, §26) — no
// editorializing — and every ownership statement cites where it came from.
import type { DataStatusId, LanguageId, RegionId, SourceTypeId } from "@/lib/taxonomy";

export interface FeedSource {
  id: string;
  name: string;
  type: SourceTypeId;
  homepage: string;
  feeds: string[]; // one or more RSS/Atom URLs; empty = headline + link only
  collector?: "agent-reach";
  listingUrls?: string[];
  ownership: string;
  ownershipSource: string;
  dataStatus: DataStatusId;
  paywalled?: boolean;
  regions: RegionId[]; // primary regions covered
  languages: LanguageId[];
  topics?: string[];
  /** Fact-check publisher: items become `fact_checks` rows, not articles. */
  factCheck?: boolean;
  verified: boolean; // set by scripts/check-feeds.ts output review
  /** Why a source has no working feed (shown nowhere in UI; for ops). */
  feedNote?: string;
}

export const FEEDS: FeedSource[] = [
  // ---- National Media ----
  {
    id: "inquirer",
    name: "Inquirer.net",
    type: "national",
    homepage: "https://www.inquirer.net",
    feeds: ["https://www.inquirer.net/feed/"],
    ownership: "Philippine Daily Inquirer, Inc. (Inquirer Group)",
    ownershipSource: "Publisher's corporate information page",
    dataStatus: "feed",
    paywalled: false,
    regions: ["ncr"],
    languages: ["en"],
    verified: true,
  },
  {
    id: "gma-news",
    name: "GMA News Online",
    type: "national",
    homepage: "https://www.gmanetwork.com/news/",
    feeds: ["https://www.gmanetwork.com/rss"],
    ownership: "GMA Network, Inc.",
    ownershipSource: "GMA Network corporate filings (PSE)",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en", "fil"],
    verified: true,
  },
  {
    id: "philstar",
    name: "The Philippine Star",
    type: "national",
    homepage: "https://www.philstar.com",
    feeds: ["https://www.philstar.com/rss/headlines", "https://www.philstar.com/rss/nation"],
    ownership: "Philstar Global Corp. (MediaQuest Holdings group)",
    ownershipSource: "Publisher's About page",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en"],
    verified: true,
  },
  {
    id: "abs-cbn",
    collector: "agent-reach", listingUrls: ["https://www.abs-cbn.com/news"],
    name: "ABS-CBN News",
    type: "national",
    homepage: "https://www.abs-cbn.com/news",
    feeds: ["https://www.abs-cbn.com/feed/"],
    ownership: "ABS-CBN Corporation (Lopez Group)",
    ownershipSource: "ABS-CBN corporate filings (PSE)",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en", "fil"],
    verified: false,
    feedNote: "HTTP 403 with identifying RSS-reader User-Agent on 2026-09-27; no working alternative discovered",
  },
  {
    id: "manila-bulletin",
    collector: "agent-reach", listingUrls: ["https://mb.com.ph"],
    name: "Manila Bulletin",
    type: "national",
    homepage: "https://mb.com.ph",
    feeds: [],
    ownership: "Manila Bulletin Publishing Corporation",
    ownershipSource: "Publisher's About page",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en"],
    verified: false,
    feedNote: "HTTP 403 (bot-blocked) as of 2026-09-27; candidate for a data partnership",
  },
  {
    id: "manila-times",
    name: "The Manila Times",
    type: "national",
    homepage: "https://www.manilatimes.net",
    feeds: ["https://www.manilatimes.net/news/feed/"],
    ownership: "The Manila Times Publishing Corporation",
    ownershipSource: "Publisher's About page",
    dataStatus: "feed",
    paywalled: true,
    regions: ["ncr"],
    languages: ["en"],
    verified: true,
  },
  {
    id: "manila-standard",
    name: "Manila Standard",
    type: "national",
    homepage: "https://manilastandard.net",
    feeds: [],
    collector: "agent-reach",
    listingUrls: ["https://manilastandard.net/"],
    feedNote: "RSS HTTP 403 with honest Alunsina reader UA on 2026-09-27; use public listing collector.",
    ownership: "Philippine Manila Standard Publishing, Inc.",
    ownershipSource: "Publisher's About page",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en"],
    verified: false,
  },
  {
    id: "businessworld",
    name: "BusinessWorld",
    type: "national",
    homepage: "https://www.bworldonline.com",
    feeds: ["https://www.bworldonline.com/feed/"],
    ownership: "BusinessWorld Publishing Corporation",
    ownershipSource: "Publisher's About page",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en"],
    topics: ["Economy", "Business"],
    verified: true,
  },
  {
    id: "businessmirror",
    name: "BusinessMirror",
    type: "national",
    homepage: "https://businessmirror.com.ph",
    feeds: [],
    ownership: "Philippine Business Daily Mirror Publishing, Inc.",
    ownershipSource: "Publisher's About page",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en"],
    topics: ["Economy", "Business"],
    verified: false,
    feedNote: "HTTP 403 (bot-blocked) as of 2026-09-27; candidate for a data partnership",
  },
  {
    id: "abante",
    name: "Abante",
    type: "national",
    homepage: "https://www.abante.com.ph",
    feeds: ["https://www.abante.com.ph/rss.xml"],
    ownership: "Monica Publishing Corporation",
    ownershipSource: "Publisher's About page",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["fil"],
    verified: false,
    feedNote: "HTTP 403 with identifying RSS-reader User-Agent on 2026-09-27; no working alternative discovered",
  },

  // ---- Independent ----
  {
    id: "rappler",
    name: "Rappler",
    type: "independent",
    homepage: "https://www.rappler.com",
    feeds: ["https://www.rappler.com/feed/"],
    ownership: "Rappler, Inc. (majority Filipino journalist-owned)",
    ownershipSource: "Rappler About page",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en", "fil"],
    verified: true,
  },
  {
    id: "pcij",
    name: "Philippine Center for Investigative Journalism",
    type: "independent",
    homepage: "https://pcij.org",
    feeds: ["https://pcij.org/feed/"],
    ownership: "Nonprofit, non-stock media foundation",
    ownershipSource: "PCIJ About page",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en"],
    verified: true,
  },
  {
    id: "bulatlat",
    name: "Bulatlat",
    type: "independent",
    homepage: "https://www.bulatlat.com",
    feeds: ["https://www.bulatlat.com/feed/"],
    ownership: "Independently owned (alternative media)",
    ownershipSource: "Bulatlat About page",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en", "fil"],
    verified: true,
  },
  {
    id: "mindanews",
    collector: "agent-reach", listingUrls: ["https://www.mindanews.com"],
    name: "MindaNews",
    type: "independent",
    homepage: "https://www.mindanews.com",
    feeds: [],
    ownership: "Mindanao News and Information Cooperative Center",
    ownershipSource: "MindaNews About page",
    dataStatus: "feed",
    regions: ["r11", "r10", "r12", "barmm", "r9", "r13"],
    languages: ["en"],
    verified: false,
    feedNote: "HTTP 403 (bot-blocked) as of 2026-09-27; candidate for a data partnership",
  },

  // ---- Fact-checkers (feed items become fact_checks, used to suppress Social blindspots) ----
  {
    id: "vera-files",
    name: "VERA Files",
    type: "independent",
    homepage: "https://verafiles.org",
    feeds: [],
    ownership: "Nonprofit media organization",
    ownershipSource: "VERA Files About page",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en", "fil"],
    factCheck: true,
    verified: false,
    feedNote: "no RSS document found as of 2026-09-27; candidate for a data partnership",
  },
  {
    id: "rappler-factcheck",
    name: "Rappler Fact Check",
    type: "independent",
    homepage: "https://www.rappler.com/newsbreak/fact-check/",
    feeds: ["https://www.rappler.com/newsbreak/fact-check/feed/"],
    ownership: "Rappler, Inc.",
    ownershipSource: "Rappler About page",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en", "fil"],
    factCheck: true,
    verified: true,
  },

  // ---- State-Run Media ----
  {
    id: "pna",
    name: "Philippine News Agency",
    type: "state",
    homepage: "https://www.pna.gov.ph",
    feeds: [],
    ownership: "Government of the Philippines (Presidential Communications Office)",
    ownershipSource: "PNA About page",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en"],
    verified: false,
    feedNote: "HTTP 404, no feed discovered as of 2026-09-27; candidate for a data partnership",
  },
  {
    id: "ptv",
    name: "PTV News",
    type: "state",
    homepage: "https://ptvnews.ph",
    feeds: ["https://ptvnews.ph/feed/"],
    ownership: "People's Television Network, Inc. (government-owned)",
    ownershipSource: "PTV About page",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en", "fil"],
    verified: true,
  },

  // ---- Government Statement ----
  {
    id: "pia",
    name: "Philippine Information Agency",
    type: "government",
    homepage: "https://pia.gov.ph",
    feeds: [],
    ownership: "Government of the Philippines (attached agency, PCO)",
    ownershipSource: "PIA About page",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en", "fil"],
    verified: false,
    feedNote: "HTTP 403 (bot-blocked) as of 2026-09-27; candidate for a data partnership",
  },
  {
    id: "senate",
    name: "Senate of the Philippines (Press Releases)",
    type: "government",
    homepage: "https://legacy.senate.gov.ph/press_release/",
    feeds: [],
    ownership: "Senate of the Philippines",
    ownershipSource: "Official website",
    dataStatus: "link",
    regions: ["ncr"],
    languages: ["en"],
    verified: false,
    feedNote: "no public feed as of 2026-09-27; candidate for a data partnership",
  },

  // ---- Primary Document ----
  {
    id: "official-gazette",
    name: "Official Gazette",
    type: "primary",
    homepage: "https://www.officialgazette.gov.ph",
    feeds: ["https://www.officialgazette.gov.ph/feed/"],
    ownership: "Government of the Philippines (Presidential Communications Office)",
    ownershipSource: "Official website",
    dataStatus: "feed",
    regions: ["ncr"],
    languages: ["en"],
    verified: true,
  },

  // ---- Regional Media ----
  {
    id: "sunstar",
    name: "SunStar",
    type: "regional",
    homepage: "https://www.sunstar.com.ph",
    feeds: ["https://www.sunstar.com.ph/feed/"],
    ownership: "SunStar Publishing, Inc.",
    ownershipSource: "SunStar About page",
    dataStatus: "feed",
    regions: ["r7", "r11", "r10", "r3", "car", "nir"],
    languages: ["en", "ceb"],
    verified: true,
  },
  {
    id: "panay-news",
    collector: "agent-reach", listingUrls: ["https://www.panaynews.net"],
    name: "Panay News",
    type: "regional",
    homepage: "https://www.panaynews.net",
    feeds: ["https://www.panaynews.net/feed/"],
    ownership: "Independently owned",
    ownershipSource: "Publisher's About page",
    dataStatus: "feed",
    regions: ["r6"],
    languages: ["en", "hil"],
    verified: true,
  },
  {
    id: "daily-guardian",
    collector: "agent-reach", listingUrls: ["https://dailyguardian.com.ph"],
    name: "Daily Guardian",
    type: "regional",
    homepage: "https://dailyguardian.com.ph",
    feeds: [],
    ownership: "Independently owned",
    ownershipSource: "Publisher's About page",
    dataStatus: "feed",
    regions: ["r6"],
    languages: ["en"],
    verified: false,
    feedNote: "HTTP 403 (bot-blocked) as of 2026-09-27; candidate for a data partnership",
  },
  {
    id: "mindanao-times",
    name: "Mindanao Times",
    type: "regional",
    homepage: "https://mindanaotimes.com.ph",
    feeds: ["https://mindanaotimes.com.ph/feed/"],
    ownership: "Independently owned",
    ownershipSource: "Publisher's About page",
    dataStatus: "feed",
    regions: ["r11"],
    languages: ["en"],
    verified: true,
  },
  {
    id: "edge-davao",
    name: "Edge Davao",
    type: "regional",
    homepage: "https://edgedavao.net",
    feeds: ["https://edgedavao.net/feed/"],
    ownership: "Independently owned",
    ownershipSource: "Publisher's About page",
    dataStatus: "feed",
    regions: ["r11"],
    languages: ["en"],
    verified: true,
  },
  {
    id: "punto",
    name: "Punto! Central Luzon",
    type: "regional",
    homepage: "https://punto.com.ph",
    feeds: ["https://punto.com.ph/feed/"],
    ownership: "Independently owned",
    ownershipSource: "Publisher's About page",
    dataStatus: "feed",
    regions: ["r3"],
    languages: ["en", "fil"],
    verified: true,
  },
  {
    id: "baguio-midland",
    name: "Baguio Midland Courier",
    type: "regional",
    homepage: "https://www.baguiomidlandcourier.com.ph",
    feeds: [],
    ownership: "Independently owned",
    ownershipSource: "Publisher's About page",
    dataStatus: "feed",
    regions: ["car"],
    languages: ["en"],
    verified: false,
    feedNote: "connection failed as of 2026-09-27; candidate for a data partnership",
  },

  {
    id: "gma-regional-amianan", name: "GMA Regional TV Balitang Amianan", type: "regional", homepage: "https://www.gmanetwork.com/regionaltv/",
    feeds: [], ownership: "GMA Network, Inc.", ownershipSource: "Publisher About page", dataStatus: "feed",
    regions: ["r1","r2","r3","car"], languages: ["fil","ilo"], verified: false,
    feedNote: "No stable desk listing; covered via GMA network RSS. Probed 2026-09-27; candidate listings discover only broad network RSS.",
  },
  {
    id: "cebu-daily-news", collector: "agent-reach", listingUrls: ["https://cebudailynews.inquirer.net/"], name: "Cebu Daily News (CDN Digital)", type: "regional", homepage: "https://cebudailynews.inquirer.net",
    feeds: [], ownership: "Philippine Daily Inquirer, Inc. (Inquirer Group)", ownershipSource: "Publisher About page", dataStatus: "feed",
    regions: ["r7"], languages: ["en","ceb"], verified: false,
    feedNote: "HTTP 403 on 2026-09-27; use Agent Reach listing collection.",
  },

  {
    id: "the-freeman", name: "The Freeman", type: "regional", homepage: "https://www.philstar.com/the-freeman",
    feeds: ['https://www.philstar.com/rss/the-freeman'], ownership: "Philstar Global Corp. (MediaQuest Holdings group)", ownershipSource: "Publisher About page", dataStatus: "feed",
    regions: ["r7"], languages: ["en"], verified: true,
    feedNote: "Section RSS returned 10 items.",
  },
  {
    id: "gma-regional-bisdak", name: "GMA Regional TV Balitang Bisdak", type: "regional", homepage: "https://www.gmanetwork.com/regionaltv/", collector: "agent-reach", listingUrls: ["https://www.gmanetwork.com/regionaltv/balitangbisdak"],
    feeds: [], ownership: "GMA Network, Inc.", ownershipSource: "Publisher About page", dataStatus: "feed",
    regions: ["r7","r8"], languages: ["ceb","fil"], verified: false,
    feedNote: "No stable desk listing; covered via GMA network RSS. Probed 2026-09-27; candidate listings discover only broad network RSS.",
  },
  {
    id: "news-today-iloilo", name: "The News Today (Iloilo)", type: "regional", homepage: "https://www.thenewstoday.info",
    feeds: [], ownership: "Ownership not yet verified", ownershipSource: "Ownership verification pending", dataStatus: "feed",
    regions: ["r6"], languages: ["en"], verified: false,
    feedNote: "Fetch failed on 2026-09-27; no working feed discovered.", collector: "agent-reach", listingUrls: ["https://www.thenewstoday.info"],
  },
  {
    id: "gma-one-western-visayas", name: "GMA Regional TV One Western Visayas", type: "regional", homepage: "https://www.gmanetwork.com/regionaltv/",
    feeds: [], ownership: "GMA Network, Inc.", ownershipSource: "Publisher About page", dataStatus: "feed",
    regions: ["r6","nir"], languages: ["hil","fil"], verified: false,
    feedNote: "No stable desk listing; covered via GMA network RSS. Probed 2026-09-27; candidate listings discover only broad network RSS.",
  },
  {
    id: "visayan-daily-star", name: "Visayan Daily Star", type: "regional", homepage: "https://visayandailystar.com",
    collector: "agent-reach", listingUrls: ["https://visayandailystar.com"],
    feeds: [], ownership: "Ownership not yet verified", ownershipSource: "Ownership verification pending", dataStatus: "feed",
    regions: ["nir"], languages: ["en","hil"], verified: false,
    feedNote: "Feed returned 10 items, but latest dated 2026-06-06 (outside 7-day ingestion window).",
  },
  {
    id: "bohol-chronicle",
    collector: "agent-reach", listingUrls: ["https://www.boholchronicle.com.ph"], name: "The Bohol Chronicle", type: "regional", homepage: "https://www.boholchronicle.com.ph",
    feeds: [], ownership: "Ownership not yet verified", ownershipSource: "Ownership verification pending", dataStatus: "feed",
    regions: ["r7"], languages: ["en","ceb"], verified: false,
    feedNote: "Homepage reachable but no feed discovered; /feed/ returned 404.",
  },
  {
    id: "gma-one-mindanao", name: "GMA Regional TV One Mindanao", type: "regional", homepage: "https://www.gmanetwork.com/regionaltv/", collector: "agent-reach", listingUrls: ["https://www.gmanetwork.com/regionaltv/onemindanao"],
    feeds: [], ownership: "GMA Network, Inc.", ownershipSource: "Publisher About page", dataStatus: "feed",
    regions: ["r11","r10","r12","r9","r13"], languages: ["fil"], verified: false,
    feedNote: "No stable desk listing; covered via GMA network RSS. Probed 2026-09-27; candidate listings discover only broad network RSS.",
  },
  {
    id: "mindanao-gold-star-daily", name: "Mindanao Gold Star Daily", type: "regional", homepage: "https://mindanaogoldstardaily.com",
    feeds: ['https://mindanaogoldstardaily.com/rss.xml'], ownership: "Ownership not yet verified", ownershipSource: "Ownership verification pending", dataStatus: "feed",
    regions: ["r10"], languages: ["en"], verified: true,
    feedNote: "Feed returned 30 items; latest dated 2026-09-25.",
  },
  {
    id: "davao-today", name: "Davao Today", type: "regional", homepage: "https://davaotoday.com",
    feeds: ['https://davaotoday.com/feed/'], ownership: "Davao Today, Inc.", ownershipSource: "Publisher About page", dataStatus: "feed",
    regions: ["r11"], languages: ["en","fil"], verified: true,
    feedNote: "Feed returned 5 items.",
  },
  {
    id: "business-week-mindanao", name: "Business Week Mindanao", type: "regional", homepage: "https://businessweekmindanao.com",
    feeds: ['https://businessweekmindanao.com/feed/'], ownership: "Ownership not yet verified", ownershipSource: "Ownership verification pending", dataStatus: "feed",
    regions: ["r10","r11"], languages: ["en"], verified: true,
    feedNote: "Feed returned 10 items.",
  },
  {
    id: "kagay-an", name: "Kagay-an.com", type: "regional", homepage: "https://www.kagay-an.com", collector: "agent-reach", listingUrls: ["https://www.kagay-an.com"],
    feeds: [], ownership: "Ownership not yet verified", ownershipSource: "Ownership verification pending", dataStatus: "feed",
    regions: ["r10"], languages: ["en"], verified: false,
    feedNote: "RSS endpoint intermittently unavailable on 2026-09-27; collector fallback enabled.",
  },
  {
    id: "cagayan-de-oro-times",
     name: "Cagayan de Oro Times", type: "regional", homepage: "https://cagayandeorotimes.com/",
    feeds: ["https://cagayandeorotimes.com/feed/"], ownership: "Ownership not yet verified", ownershipSource: "Ownership verification pending", dataStatus: "feed",
    regions: ["r10"], languages: ["en"], verified: true,
    feedNote: "Feed discovered on 2026-09-27; latest item dated 2026-09-22.",
  },
  {
    id: "mindanao-daily-news", name: "Mindanao Daily News", type: "regional", homepage: "https://mindanaodailynews.com",
    feeds: ['https://mindanaodailynews.com/feed/'], ownership: "Ownership not yet verified", ownershipSource: "Ownership verification pending", dataStatus: "feed",
    regions: ["r10","r11","r12","r13"], languages: ["en"], verified: true,
    feedNote: "Feed returned 10 items.",
  },
  {
    id: "daily-tribune", name: "Daily Tribune", type: "national", homepage: "https://tribune.net.ph",
    feeds: ['https://tribune.net.ph/rss.xml'], ownership: "The Tribune Media Group, Inc.", ownershipSource: "Publisher About page", dataStatus: "feed",
    regions: ["ncr"], languages: ["en"], verified: true,
    feedNote: "RSS discovery returned 40 items.",
  },
  {
    id: "one-news", name: "TV5 / One News / One PH", type: "national", homepage: "https://www.onenews.ph",
    feeds: [], ownership: "MediaQuest Holdings, Inc.", ownershipSource: "Publisher About page", dataStatus: "feed",
    regions: ["ncr"], languages: ["en","fil"], verified: false,
    feedNote: "No working RSS feed discovered; One PH has no verified separate listing.", collector: "agent-reach", listingUrls: ["https://www.onenews.ph"],
  },
  // ---- Community ----
  {
    id: "bombo-radyo",
    name: "Bombo Radyo",
    type: "community",
    homepage: "https://www.bomboradyo.com",
    feeds: ["https://www.bomboradyo.com/feed/"],
    ownership: "Ownership not yet verified",
    ownershipSource: "Ownership verification pending",
    dataStatus: "feed",
    regions: [], // Network-wide feed; tag individual places from reporting.
    languages: ["fil", "en"],
    verified: true,
    feedNote: "Radio network feed returned 10 items on 2026-09-27; no image fields",
  },
  {
    id: "brigada-news",
    name: "Brigada News",
    type: "community",
    homepage: "https://www.brigadanews.ph",
    feeds: ["https://www.brigadanews.ph/feed/"],
    ownership: "Ownership not yet verified",
    ownershipSource: "Ownership verification pending",
    dataStatus: "feed",
    regions: [], // Network-wide feed, not a single-region newsroom.
    languages: ["fil", "en"],
    verified: true,
    feedNote: "Radio network feed returned 10 items on 2026-09-27; no image fields",
  },
  {
    id: "nordis",
    name: "Northern Dispatch",
    type: "community",
    homepage: "https://nordis.net",
    feeds: [],
    ownership: "Community-based media organization",
    ownershipSource: "Nordis About page",
    dataStatus: "feed",
    regions: ["car", "r1", "r2"],
    languages: ["en", "ilo"],
    verified: false,
    feedNote: "HTTP 429 (rate-limited) as of 2026-09-27; candidate for a data partnership",
  },
];
