ALTER TABLE contributors ADD COLUMN verified_at timestamptz, ADD COLUMN region text,
 ADD COLUMN source_id text REFERENCES sources(id) ON DELETE SET NULL, ADD COLUMN active boolean NOT NULL DEFAULT true;
ALTER TABLE stories ADD COLUMN hidden boolean NOT NULL DEFAULT false;
ALTER TABLE flags ADD COLUMN resolved_at timestamptz, ADD COLUMN resolution_note text,
 ADD CONSTRAINT flags_status_check CHECK (status IN ('open','resolved','dismissed'));
CREATE TABLE pitches (
 pitch_id text PRIMARY KEY, reporter_id text NOT NULL REFERENCES contributors(id) ON DELETE CASCADE,
 topic text NOT NULL, region text, angle text NOT NULL, timeframe text NOT NULL,
 status text NOT NULL DEFAULT 'pitched' CHECK (status IN ('pitched','in_progress','published')),
 linked_blindspot_id integer REFERENCES blindspots(id) ON DELETE SET NULL,
 linked_story_id text REFERENCES stories(id) ON DELETE SET NULL,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 status_changed_at timestamptz NOT NULL DEFAULT now(),
 screening_status text NOT NULL DEFAULT 'pending' CHECK (screening_status IN ('pending','passed','flagged')),
 screening_categories jsonb NOT NULL DEFAULT '[]' CHECK (jsonb_typeof(screening_categories) = 'array'), screened_at timestamptz
);
CREATE TABLE pitch_publications (
 pitch_id text PRIMARY KEY REFERENCES pitches(pitch_id) ON DELETE CASCADE,
 article_id text NOT NULL UNIQUE REFERENCES articles(id) ON DELETE CASCADE,
 url text NOT NULL, headline text NOT NULL, excerpt text NOT NULL,
 screening_status text NOT NULL DEFAULT 'pending' CHECK (screening_status IN ('pending','passed','flagged')),
 screening_categories jsonb NOT NULL DEFAULT '[]' CHECK (jsonb_typeof(screening_categories) = 'array'), screened_at timestamptz
);
CREATE INDEX pitches_activity ON pitches(updated_at DESC);
CREATE INDEX pitches_reporter ON pitches(reporter_id);
CREATE TABLE admin_audit (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, at timestamptz NOT NULL DEFAULT now(),
 action text NOT NULL, entity text NOT NULL, entity_id text, detail jsonb NOT NULL DEFAULT '{}'
);
DO $$ DECLARE t text; r text; BEGIN
 FOREACH t IN ARRAY ARRAY['pitches','pitch_publications','admin_audit'] LOOP
  EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t);
  FOREACH r IN ARRAY ARRAY['anon','authenticated'] LOOP
   IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname=r) THEN EXECUTE format('REVOKE ALL ON public.%I FROM %I',t,r); END IF;
  END LOOP;
 END LOOP;
END $$;
-- These views are used only through the server DB owner, never PostgREST.
CREATE VIEW public_articles AS SELECT a.* FROM articles a
 WHERE NOT EXISTS (SELECT 1 FROM pitch_publications p WHERE p.article_id=a.id AND p.screening_status <> 'passed')
 AND NOT EXISTS (SELECT 1 FROM stories s WHERE s.id=a.story_id AND s.hidden);
CREATE VIEW public_stories AS SELECT s.* FROM stories s WHERE NOT hidden
 AND EXISTS (SELECT 1 FROM public_articles a WHERE a.story_id=s.id);
DO $$ DECLARE r text; BEGIN
 FOREACH r IN ARRAY ARRAY['anon','authenticated'] LOOP
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname=r) THEN
   EXECUTE format('REVOKE ALL ON public.public_articles, public.public_stories FROM %I',r);
  END IF;
 END LOOP;
END $$;
